# Bài tập 1: Numpy Cơ Bản

In [53]:
#Import Lib
import numpy as np
import matplotlib . image as mpimg
import pandas as pd

EX1: Initialize 1D Array (0,9)

In [9]:
arr = np.arange(0,10,1)
print(arr,type(arr),sep="\n")

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


EX2: Initialize Bool 3x3 Array

In [12]:
arr1 = np . ones ((3 ,3) ) > 0
arr2 = np . ones ((3 ,3) , dtype = bool )
arr3 = np . full ((3 ,3) , fill_value = True , dtype = bool )

print(type(arr1[0][0]),type(arr2[0][0]),type(arr3[0][0]), sep="\n")

<class 'numpy.bool_'>
<class 'numpy.bool_'>
<class 'numpy.bool_'>


EX3: Run code

In [13]:
arr = np . arange (0 ,10)
print ( arr [ arr %2 == 1])

[1 3 5 7 9]


EX4: Run code

In [14]:
arr = np . arange (0 ,10)
arr [ arr %2 ==1] = -1
print ( arr )

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


EX5: Run code

In [15]:
arr = np.arange(10)
arr_2d = arr.reshape(2 , -1)
print ( arr_2d )

[[0 1 2 3 4]
 [5 6 7 8 9]]


EX6: Run code

In [16]:
arr1 = np . arange (10) . reshape (2 , -1)
arr2 = np . repeat (1 ,10) . reshape (2 , -1)
c = np . concatenate ([ arr1 , arr2 ] , axis =0)
print (" Result : \n", c )

 Result : 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


EX7: Run code

In [17]:
arr1 = np . arange (10) . reshape (2 , -1)
arr2 = np . repeat (1 ,10) . reshape (2 , -1)
c = np . concatenate ([ arr1 , arr2 ] , axis =1)
print ("C = ", c )

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


EX8: Run code

In [18]:
arr = np . array ([1 ,2 ,3])
print ( np . repeat ( arr ,3) )
print ( np . tile ( arr ,3) )

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


EX9: Run code

In [19]:
a = np . array ([2 ,6 ,1 ,9 ,10 ,3 ,27])
index = np . where ((a >=5) &( a <=10) )
print (" result ", a [ index ])

 result  [ 6  9 10]


EX10: Run code

In [24]:
def maxx (x , y) :
    if x >= y :
        return x
    else :
        return y

a = np . array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np . array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

pair_max = np . vectorize ( maxx , otypes =[ float ])
print ( pair_max (a , b ) )

[6. 7. 9. 8. 9. 7. 5.]


EX11: Run code

In [25]:
a = np . array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np . array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

print (" Result ", np . where (a <b , b , a ) )

 Result  [6 7 9 8 9 7 5]


# Bài tập 2: Xử lý ảnh

EX12: Run code

In [43]:
# Lightness
img = mpimg . imread (r'dog.jpeg')
gray_img_01 = np.mean([np.max(img, axis=2), np.min(img, axis=2)], axis=0)
gray_img_01 [0, 0]

102.5

EX13: Run code

In [44]:
# Average
gray_img_02 = np.mean(img, axis=2)
gray_img_02 [0 , 0]

107.66666666666667

EX14: Run code

In [51]:
# Luminosity
def grayscale_luminosity(r,g,b):
    return 0.21*r + 0.72*g + 0.07*b

gray_img_03 = np.vectorize(grayscale_luminosity)(img[:,:,0], img[:,:,1], img[:,:,2])
gray_img_03 [0 , 0]

126.22999999999999

# Bài tập 3: Phân tích dữ liệu dạng bảng

EX15: Run code

In [59]:
df = pd.read_csv(r"advertising.csv")
data = df.to_numpy()

# Get "Sale" column index
sales_column_index = df.columns.get_loc('Sales')

# Extract the "Sales" column
sales = data[:, sales_column_index]

# Find the maximum value and its corresponding index
max_value = np.max(sales)
max_index = np.argmax(sales)

print(f"Max: {max_value} - Index: {max_index}")

Max: 27.0 - Index: 175


EX16: Run code

In [68]:
# Get "TV" column index
tv_column_index = df.columns.get_loc('TV')

# Extract the "TV" column
tv = data[:, tv_column_index]

# Find the maximum value and its corresponding index
mean_value = np.mean(tv)

print(f"Mean: {mean_value}")

Mean: 147.0425


EX17: Run code

In [67]:
count_sales_above_20 = np.sum(data[:, sales_column_index] >= 20)
print("Number of records with Sales >= 20:", count_sales_above_20)

Number of records with Sales >= 20: 40


EX18: Run code

In [72]:
# Get "Radio" column index
radio_column_index = df.columns.get_loc('Radio')

# Find the maximum value and its corresponding index
average_radio_sales_above_15 = np.mean(data[data[:, sales_column_index] >= 15, radio_column_index])

print("Average Radio where Sales >= 15:", average_radio_sales_above_15)

Average Radio where Sales >= 15: 26.22293577981651


EX19: Run code

In [74]:
# Get "Radio" column index
newspaper_column_index = df.columns.get_loc('Newspaper')

# Find the maximum value and its corresponding index
sum_sales_newspaper_above_mean = np.sum(data[data[:, newspaper_column_index] > np.mean(data[:,newspaper_column_index]), sales_column_index])

print("Average Radio where Sales >= 15:", sum_sales_newspaper_above_mean)

Average Radio where Sales >= 15: 1405.1


EX20: Run code

In [76]:
# Calculate the mean of the 'Sales' column
A = np.mean(sales)

# Define a function to label values based on conditions
def label_scores(value, A):
    if value > A:
        return 'Good'
    elif value < A:
        return 'Bad'
    else:
        return 'Average'

# Create a new array 'scores' based on conditions using np.vectorize
scores = np.vectorize(label_scores)(sales, A)

# Print the result for scores[7:10]
print("Scores from index 7 to 9:", scores[7:10])

Scores from index 7 to 9: ['Bad' 'Bad' 'Good']


EX21: Run code

In [77]:
A = np.mean(sales)

nearest_value_index = np.abs(df['Sales'] - A).idxmin()
nearest_value_to_A = df.loc[nearest_value_index, 'Sales']

# Define a function to label values based on conditions
def label_scores(value, A):
    if value > A:
        return 'Good'
    elif value < A:
        return 'Bad'
    else:
        return 'Average'

# Create a new array 'scores' based on conditions using np.vectorize
scores = np.vectorize(label_scores)(df['Sales'], nearest_value_to_A)

# Print the result for scores[7:10]
print("Scores from index 7 to 9:", scores[7:10])

Scores from index 7 to 9: ['Bad' 'Bad' 'Good']
